### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by Oshawk** [tomvanbraeckel/etherdeltaclientservice.py#1]
Hello,

I have no experience with the EtherDelta API and it seems very much more complicated than any other exchanges. How easy would it be for me to:
- List all available tokens with their best buy and sell prices as well as the amount being offered etc.
- Make a buy/sell trade at the best price for a specific token.

Any help would be much appreciated.

**Comment by tomvanbraeckel** [comment]
Hi,

Thanks for reaching out.

I think the first question is a generic Etherdelta support question that I don't know the answer to. I am in no way affiliated with Etherdelta, I just made this API client, which does not output the list that you mention.

As for the second question, doing a trade at the best price for a specific token is exactly what the code examples here do, so I consider that to be very easy. Have a look at taker.py

By the way, the official Etherdelta-maintained versions of these code examples are now hosted at https://github.com/etherdelta/bots/

Kind regards,

Tom.

**Comment by Oshawk** [comment]
Thanks,

So is there no way that I can fetch a list of available tokens? I am really confused, is it because they are smart contracts? if so, where can I learn about how EtherDelta works?

Thanks,
Joseph.
(Sorry for bothering you.)
